plugin:
  id: peptide-library-check
  name: Peptide Library Check
  version: 1.0.0
  description: Check if peptides from experimental data are present in a FASTA library by generating tryptic peptides with configurable miss cleavages
  author: Cauldron Team
  category: utilities
  icon: fact_check
  repository: https://github.com/noatgnu/peptide-library-check-plugin

runtime:
  environments: ["python"]
  entrypoint: library_check_peptide.py

inputs:
  - name: file_path
    label: Input Peptide File
    type: file
    required: true
    description: Tab-separated or CSV file containing experimental peptide data
    file_types:
      - .txt
      - .tsv
      - .csv

  - name: peptide_column
    label: Peptide Sequence Column
    type: column
    required: true
    description: Column containing peptide sequences to check
    source: file_path

  - name: fasta_file
    label: FASTA Library File
    type: file
    required: true
    description: FASTA file containing protein sequences to generate tryptic peptide library
    file_types:
      - .fasta
      - .fa

  - name: miss_cleavage
    label: Missed Cleavages
    type: number
    required: false
    default: 2
    min: 0
    max: 5
    description: Maximum number of missed cleavages to consider when generating tryptic peptides

  - name: min_length
    label: Minimum Peptide Length
    type: number
    required: false
    default: 5
    min: 1
    max: 50
    description: Minimum length of peptides to include in the library

execution:
  argsMapping:
    file_path: "--input"
    peptide_column: "--peptide-col"
    fasta_file: "--fasta"
    miss_cleavage: "--miss-cleavage"
    min_length: "--min-length"
  outputDir: "--output-dir"
  requirements:
    python: ">=3.10"
    pythonRequirementsFile: requirements.txt

outputs:
  - name: peptide_in_library.txt
    path: peptide_in_library.txt
    type: data
    description: Tab-separated file with a "Found" column indicating whether each peptide was found in the FASTA library
